//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.DMS.WebServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchesReport
    {
        public int BatchID { get; set; }
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public System.DateTime ActualStartTime { get; set; }
        public System.DateTime ActualEndTime { get; set; }
        public string Recipe_RID { get; set; }
        public string Description { get; set; }
    }
}
