//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP.DMS.WebServices.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Line
    {
        public int LineId { get; set; }
        public System.Guid LineGuid { get; set; }
        public string LineName { get; set; }
        public string SerialNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
